### ISSUE TITLE
PlayerSetup.cs en double

### ISSUE THREAD

**Issue by hunabku94** [TUTOUNITYFR/TUTO-FPS-2018#1]
Le fichiers : 
- TUTO-FPS-2018/SERIE_FPS_2018/Assets/PlayerSetup.cs
- TUTO-FPS-2018/SERIE_FPS_2018/Assets/PlayerSetup.cs.meta
sont de trop et causent une erreur.

**Comment by TUTOUNITYFR** [comment]
Fichiers supprimés.
